[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "write", path = "output" },
    { access = "read", path = "src/1.txt" },
    { access = "read", path = "src/2.txt" }
]
block_gas_limit = 9223372036854775807
optimizer = true
optimizer_runs = 200
via_ir = true
stack = 2048
evm_version = "london"
optimizer_details = { yul = true, yulDetails = { stackAllocation = true } }